### ISSUE TITLE
Can't able to receive the data from other mobiles for particular devices

### ISSUE THREAD

**Issue by pandalovedev19** [chirp/chirp-android-examples#19]
Previously I was using 3.6.+ dependency version which causes crash issue in the higher end devices like S8, S9, pixel 2, pixel 3, etc...

I have refereed the stack overflow they mentioned that the crash issue is based on the current SDK and asked us to update the latest version.

 The current latest version on chirp is 3.9.5 which was released a month ago(June 2019).

If we use the latest version the crash issue is fixed but the receiving functionality is not working.

I have tested the latest version of the SDK on the following devices S8, MI Note 4, Nokia TA- 1032, Moto E with the demo project.

**Comment by dinuchiriac** [comment]
Can you come with more details about:
 - What exactly is not working, the device is just silently running or you are getting some errors/crashes, or maybe decoding is failing?
 - What protocol are you using? Also make sure you using the same protocol on the both, sender and receiver devices.
 - Can you share some logs from the devices you are testing?

**Comment by pandalovedev19** [comment]
The decoding is not working on some devices like S8, Mi Note 4 etc...

I'm using ultrasonic-multichannel for both sender and receiver

I'm not getting any log response in the IDE

**Comment by dinuchiriac** [comment]
We are not able to reproduce the issue here @pandalovedev19.
Can you send us more details about what exactly are you doing? 
Also, here are a couple tips to check when debugging:
- When sending, make sure volume is high enough and the device is not muted. 
- Try using different protocol like standard one and check if it's still not working. Standard protocol is audible so you should be able to hear when data is being sent.
- Make sure you are using the same protocol on both devices, sender and receiver.
